# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89529e2ff5df4781fd60414679ede8baed96fb7fcf144954141a33489706bb8dfa1193a88b064e3f46bf6e8b79f24ee31ecc417e3a489d8e3b60934977e19a6e

test:
  secret_key_base: c3ffae698685b58a5de127f712d55bb1977fc2345ba870ecfd026bf908ef2d5a391acc15480c3819c8e1ea10731ab605dc4eb8ff460c48bf8e9403d723562150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
